# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ammar Shah
tagline:          'Freshly published thoughts on the world!'
description:      'Ammar Shah is a writer and Front-End-Dev based in Karachi, Pakistan'
url:              ammaralishah.github.io
baseurl:          /

author:
  name:           'Ammar Shah'
  url:            https://twitter.com/AmmarAliShahK

plugins: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Filtering Content
show_drafts: null
