# Site settings
title: Ammar Shah
email: ammar@ammaralishah.me
description: > # this means to ignore newlines until "baseurl:"
  Ammar Shah is a freelance developer based in Karachi, Pakistan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ammaralishah.me" # the base hostname & protocol for your site
twitter_username: AmmarAliShahK
github_username:  AmmarAliShah

# Build settings
markdown: kramdown
