# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ammar Says
tagline:          'Freshly published thoughts on the world!'
description:      'Freshly published thoughts on the world!'
url:              ammaralishah.github.io
baseurl:          /

author:
  name:           'Ammar Shah'
  url:            https://twitter.com/AmmarAliShahK

gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Filtering Content
show_drafts: null
