# Site
name: Ammar Shah
description: "Ammar Shah is a writer, Digital Marketer and Software Engineer based in Karachi, Pakistan"
meta_description: "Ammar Shah is a writer, Digital Marketer and Software Engineer based in Karachi, Pakistan"
logo: 'assets/images/logo.png'
paginate: 12
baseurl:
email: 'hi@ammarshah.com'
google_analytics: 'UA-69248838-4'
disqus: 'ammarsays'

# Authors
authors:
  ammar:
    name: Ammar Shah
    display_name: Ammar Shah
    gravatar: syedammarali24@gmail.com
    email: hi@ammarshah.com
    web: https://ammarshah.com/about
    twitter: https://twitter.com/AmmarAliShahK
    description: "Ammar Shah is a writer, Digital Marketer and Software Engineer based in Karachi, Pakistan"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
    - year
    - month
  layout: archive
  permalinks:
    category: '/category/:name/'
    month: '/:year/:month/'

# Other
markdown: kramdown
highlighter: rouge
